module Cache where

import BlogDataSource
import Haxl.Core

loadCache :: GenHaxl u ()
loadCache = do
  cacheRequest (FetchPosts) (Right ([PostId 1,PostId 2,PostId 3,PostId 4,PostId 5,PostId 6,PostId 7,PostId 8,PostId 9,PostId 10,PostId 11,PostId 12]))
  cacheRequest (FetchPostInfo (PostId 7)) (Right (PostInfo {postId = PostId 7, postDate = Date 1.41647796e9, postTopic = "topic1"}))
  cacheRequest (FetchPostInfo (PostId 6)) (Right (PostInfo {postId = PostId 6, postDate = Date 1.4164779e9, postTopic = "topic3"}))
  cacheRequest (FetchPostInfo (PostId 5)) (Right (PostInfo {postId = PostId 5, postDate = Date 1.41647784e9, postTopic = "topic2"}))
  cacheRequest (FetchPostInfo (PostId 4)) (Right (PostInfo {postId = PostId 4, postDate = Date 1.41647778e9, postTopic = "topic1"}))
  cacheRequest (FetchPostInfo (PostId 3)) (Right (PostInfo {postId = PostId 3, postDate = Date 1.41647772e9, postTopic = "topic3"}))
  cacheRequest (FetchPostInfo (PostId 2)) (Right (PostInfo {postId = PostId 2, postDate = Date 1.41647766e9, postTopic = "topic2"}))
  cacheRequest (FetchPostInfo (PostId 1)) (Right (PostInfo {postId = PostId 1, postDate = Date 1.4164776e9, postTopic = "topic1"}))
  cacheRequest (FetchPostInfo (PostId 12)) (Right (PostInfo {postId = PostId 12, postDate = Date 1.41647826e9, postTopic = "topic3"}))
  cacheRequest (FetchPostInfo (PostId 11)) (Right (PostInfo {postId = PostId 11, postDate = Date 1.4164782e9, postTopic = "topic2"}))
  cacheRequest (FetchPostInfo (PostId 10)) (Right (PostInfo {postId = PostId 10, postDate = Date 1.41647814e9, postTopic = "topic1"}))
  cacheRequest (FetchPostInfo (PostId 9)) (Right (PostInfo {postId = PostId 9, postDate = Date 1.41647808e9, postTopic = "topic3"}))
  cacheRequest (FetchPostInfo (PostId 8)) (Right (PostInfo {postId = PostId 8, postDate = Date 1.41647802e9, postTopic = "topic2"}))
  cacheRequest (FetchPostViews (PostId 12)) (Right (100))
  cacheRequest (FetchPostViews (PostId 9)) (Right (400))
  cacheRequest (FetchPostViews (PostId 8)) (Right (500))
  cacheRequest (FetchPostViews (PostId 11)) (Right (200))
  cacheRequest (FetchPostViews (PostId 10)) (Right (300))
  cacheRequest (FetchPostViews (PostId 5)) (Right (800))
  cacheRequest (FetchPostViews (PostId 4)) (Right (900))
  cacheRequest (FetchPostViews (PostId 7)) (Right (600))
  cacheRequest (FetchPostViews (PostId 6)) (Right (700))
  cacheRequest (FetchPostViews (PostId 1)) (Right (1200))
  cacheRequest (FetchPostViews (PostId 3)) (Right (1000))
  cacheRequest (FetchPostViews (PostId 2)) (Right (1100))
  cacheRequest (FetchPostContent (PostId 10)) (Right ("example content 10"))
  cacheRequest (FetchPostContent (PostId 11)) (Right ("example content 11"))
  cacheRequest (FetchPostContent (PostId 8)) (Right ("example content 8"))
  cacheRequest (FetchPostContent (PostId 9)) (Right ("example content 9"))
  cacheRequest (FetchPostContent (PostId 12)) (Right ("example content 12"))
  cacheRequest (FetchPostContent (PostId 2)) (Right ("example content 2"))
  cacheRequest (FetchPostContent (PostId 3)) (Right ("example content 3"))
  cacheRequest (FetchPostContent (PostId 1)) (Right ("example content 1"))
  cacheRequest (FetchPostContent (PostId 4)) (Right ("example content 4"))
  cacheRequest (FetchPostContent (PostId 5)) (Right ("example content 5"))
